"""MCP server exposing Seerr's REST API (OpenAPI 3.0.2, /api/v1) as tools.

Full coverage of every JSON-producing endpoint under /api/v1 (deprecated
`/blacklist/*` aliases, sunset 2026-06-01, are excluded in favour of the
`/blocklist/*` routers), but exposed as 15 resource-scoped *portmanteau*
tools instead of one tool per endpoint. Each portmanteau tool (e.g.
seerr_requests, seerr_settings_notifications) takes an `operation` enum plus
an `arguments` dict; see AGENTS.md for the rationale (a 200+-tool server
blows the MCP context budget on session start).

The vendored spec at tests/data/seerr_openapi.yml (seerr-team/seerr develop
HEAD 39ff48c650d30ced0516574c55914d0bd26c9983) still generates one async
function per endpoint into `_TOOL_REGISTRY` via scripts/generate_registry.py
- keep it in sync with the spec (see AGENTS.md). Those functions are no
longer registered as individual MCP tools; `_GROUPS` below buckets them by
resource, and `_register_group` wraps each bucket in a single dispatching
tool that calls the right function by name. Nothing about the endpoint
functions themselves changes - grouping is purely a registration-time
concern. Seerr's domain shape doesn't match the other *arr servers (settings
alone is 82/208 endpoints), so `_GROUPS` here is its own taxonomy, not the
one shared by radarr/sonarr/bookshelf.

Auth is the X-Api-Key header, generated in Seerr Settings > General. An
optional X-API-User header impersonates a specific user id (default: user 1).
A group tool is marked readOnlyHint=True only when every operation in it is
a GET that isn't also flagged `force_write` (one endpoint, `GET
/settings/discover/reset`, mutates state despite being a GET - see
`_TOOL_REGISTRY`'s `force_write` key); mixed groups carry no hints. Bodies
are passed as opaque dicts/lists. build_client points at the origin and
appends /api/v1, matching the spec's base path.
"""

import inspect
import os
import sys
from typing import Any, Literal
from urllib.parse import quote

import httpx
from fastmcp import FastMCP
from fastmcp.exceptions import ToolError
from fastmcp.tools import Tool
from mcp.types import ToolAnnotations

READONLY = ToolAnnotations(readOnlyHint=True)
WRITE = ToolAnnotations(readOnlyHint=False, destructiveHint=False)
DESTRUCTIVE = ToolAnnotations(readOnlyHint=False, destructiveHint=True)

# Seerr responses are plain JSON. `dict[str, Any]` (not bare `Any`) matters
# here: FastMCP needs a concrete schema to build MCP structured content, and
# skips that step entirely for an `Any` return type -- which silently makes
# Client.call_tool's `.data` come back None for any tool returning a JSON array
# (seerr_list_request and friends). Verified against fastmcp 3.4.7.
JSONObj = dict[str, Any]
JSONVal = JSONObj | list[Any]

mcp = FastMCP("seerr-mcp")

_client: httpx.AsyncClient | None = None


def build_client(
    base_url: str,
    api_key: str | None,
    api_user: str | None = None,
    transport: httpx.BaseTransport | None = None,
) -> httpx.AsyncClient:
    """Client pinned to {origin}/api/v1 (the spec base path)."""
    headers = {"X-Api-Key": api_key} if api_key else {}
    if api_user:
        headers["X-API-User"] = api_user
    return httpx.AsyncClient(base_url=f"{base_url.rstrip('/')}/api/v1", headers=headers, transport=transport)


async def _req(
    method: str,
    path: str,
    params: dict[str, Any] | None = None,
    json_body: JSONVal | None = None,
) -> JSONVal:
    assert _client is not None, "client not configured"
    r = await _client.request(method, path, params=params, json=json_body)
    if r.status_code >= 400:
        try:
            msg = r.json().get("message", r.text)
        except ValueError:
            msg = r.text
        raise ToolError(f"Seerr API {r.status_code}: {msg}")
    if not r.text:
        return {}
    return r.json()


def _omit(params: dict[str, Any]) -> dict[str, Any]:
    """Drop keys whose values are empty/None so the API's defaults apply."""
    return {k: v for k, v in params.items() if v not in ("", None)}


# Resource groups for portmanteau registration. Every _TOOL_REGISTRY name
# must appear in exactly one group - see test_all_registry_names_grouped.
# Seerr's own taxonomy (settings-heavy), not the shared *arr one.
_GROUPS: dict[str, tuple[str, ...]] = {
    "seerr_settings_general": (
        'seerr_add_discover_slider',
        'seerr_cancel_job',
        'seerr_create_settings_jellyfin',
        'seerr_create_settings_jellyfin_sync',
        'seerr_create_settings_main',
        'seerr_create_settings_metadatas_test',
        'seerr_create_settings_network',
        'seerr_create_settings_plex',
        'seerr_create_settings_plex_sync',
        'seerr_create_settings_radarr',
        'seerr_create_settings_radarr_test',
        'seerr_create_settings_sonarr',
        'seerr_create_settings_sonarr_test',
        'seerr_create_settings_tautulli',
        'seerr_delete_discover_slider',
        'seerr_delete_settings_radarr',
        'seerr_delete_settings_sonarr',
        'seerr_flush_cache',
        'seerr_flush_dns_cache',
        'seerr_get_settings_radarr_profiles',
        'seerr_initialize_app',
        'seerr_list_discover_sliders',
        'seerr_list_settings_about',
        'seerr_list_settings_cache',
        'seerr_list_settings_jellyfin',
        'seerr_list_settings_jellyfin_library',
        'seerr_list_settings_jellyfin_sync',
        'seerr_list_settings_jellyfin_users',
        'seerr_list_settings_jobs',
        'seerr_list_settings_logs',
        'seerr_list_settings_main',
        'seerr_list_settings_metadatas',
        'seerr_list_settings_network',
        'seerr_list_settings_plex',
        'seerr_list_settings_plex_devices_servers',
        'seerr_list_settings_plex_library',
        'seerr_list_settings_plex_sync',
        'seerr_list_settings_plex_users',
        'seerr_list_settings_public',
        'seerr_list_settings_radarr',
        'seerr_list_settings_sonarr',
        'seerr_list_settings_tautulli',
        'seerr_regenerate_api_key',
        'seerr_reset_discover_sliders',
        'seerr_run_job',
        'seerr_schedule_job',
        'seerr_update_discover_slider',
        'seerr_update_discover_sliders',
        'seerr_update_settings_metadatas',
        'seerr_update_settings_radarr',
        'seerr_update_settings_sonarr',
    ),
    "seerr_settings_notifications": (
        'seerr_create_settings_notifications_discord',
        'seerr_create_settings_notifications_discord_test',
        'seerr_create_settings_notifications_email',
        'seerr_create_settings_notifications_email_test',
        'seerr_create_settings_notifications_gotify',
        'seerr_create_settings_notifications_gotify_test',
        'seerr_create_settings_notifications_ntfy',
        'seerr_create_settings_notifications_ntfy_test',
        'seerr_create_settings_notifications_pushbullet',
        'seerr_create_settings_notifications_pushbullet_test',
        'seerr_create_settings_notifications_pushover',
        'seerr_create_settings_notifications_pushover_test',
        'seerr_create_settings_notifications_slack',
        'seerr_create_settings_notifications_slack_test',
        'seerr_create_settings_notifications_telegram',
        'seerr_create_settings_notifications_telegram_test',
        'seerr_create_settings_notifications_webhook',
        'seerr_create_settings_notifications_webhook_test',
        'seerr_create_settings_notifications_webpush',
        'seerr_create_settings_notifications_webpush_test',
        'seerr_list_pushover_sounds',
        'seerr_list_settings_notifications_discord',
        'seerr_list_settings_notifications_email',
        'seerr_list_settings_notifications_gotify',
        'seerr_list_settings_notifications_ntfy',
        'seerr_list_settings_notifications_pushbullet',
        'seerr_list_settings_notifications_pushover',
        'seerr_list_settings_notifications_slack',
        'seerr_list_settings_notifications_telegram',
        'seerr_list_settings_notifications_webhook',
        'seerr_list_settings_notifications_webpush',
    ),
    "seerr_users": (
        'seerr_batch_update_users',
        'seerr_create_user',
        'seerr_create_user_settings_linked_accounts_jellyfin',
        'seerr_create_user_settings_linked_accounts_jellyfin_quickconnect',
        'seerr_create_user_settings_linked_accounts_plex',
        'seerr_create_user_settings_main',
        'seerr_create_user_settings_notifications',
        'seerr_create_user_settings_password',
        'seerr_create_user_settings_permissions',
        'seerr_delete_user',
        'seerr_delete_user_push_subscription',
        'seerr_delete_user_settings_linked_accounts_jellyfin',
        'seerr_delete_user_settings_linked_accounts_plex',
        'seerr_get_user',
        'seerr_get_user_jellyfin',
        'seerr_get_user_push_subscription',
        'seerr_get_user_quota',
        'seerr_get_user_requests',
        'seerr_get_user_settings_main',
        'seerr_get_user_settings_notifications',
        'seerr_get_user_settings_password',
        'seerr_get_user_settings_permissions',
        'seerr_get_user_watch_data',
        'seerr_get_user_watchlist',
        'seerr_import_jellyfin_users',
        'seerr_import_plex_users',
        'seerr_list_user',
        'seerr_list_user_push_subscriptions',
        'seerr_register_push_subscription',
        'seerr_update_user',
    ),
    "seerr_discover": (
        'seerr_get_discover_keyword_movies',
        'seerr_get_discover_movies_genre',
        'seerr_get_discover_movies_language',
        'seerr_get_discover_movies_studio',
        'seerr_get_discover_tv_genre',
        'seerr_get_discover_tv_language',
        'seerr_get_discover_tv_network',
        'seerr_get_keyword',
        'seerr_get_network',
        'seerr_get_studio',
        'seerr_list_backdrops',
        'seerr_list_certifications_movie',
        'seerr_list_certifications_tv',
        'seerr_list_discover_genreslider_movie',
        'seerr_list_discover_genreslider_tv',
        'seerr_list_discover_movies',
        'seerr_list_discover_movies_upcoming',
        'seerr_list_discover_trending',
        'seerr_list_discover_tv',
        'seerr_list_discover_tv_upcoming',
        'seerr_list_discover_watchlist',
        'seerr_list_genres_movie',
        'seerr_list_genres_tv',
        'seerr_list_languages',
        'seerr_list_regions',
        'seerr_list_watchproviders_movies',
        'seerr_list_watchproviders_regions',
        'seerr_list_watchproviders_tv',
    ),
    "seerr_media_titles": (
        'seerr_get_collection',
        'seerr_get_movie',
        'seerr_get_movie_ratings',
        'seerr_get_movie_ratingscombined',
        'seerr_get_movie_recommendations',
        'seerr_get_movie_similar',
        'seerr_get_person',
        'seerr_get_person_combined_credits',
        'seerr_get_tv',
        'seerr_get_tv_ratings',
        'seerr_get_tv_recommendations',
        'seerr_get_tv_season',
        'seerr_get_tv_similar',
    ),
    "seerr_auth": (
        'seerr_authenticate_jellyfin_quickconnect',
        'seerr_check_jellyfin_quickconnect',
        'seerr_get_me',
        'seerr_initiate_jellyfin_quickconnect',
        'seerr_login_jellyfin',
        'seerr_login_local',
        'seerr_login_plex',
        'seerr_logout',
        'seerr_request_password_reset',
        'seerr_reset_password',
    ),
    "seerr_issues": (
        'seerr_create_issue',
        'seerr_create_issue_comment',
        'seerr_delete_issue',
        'seerr_delete_issuecomment',
        'seerr_get_issue',
        'seerr_get_issuecomment',
        'seerr_list_issue',
        'seerr_list_issue_count',
        'seerr_set_issue_status',
        'seerr_update_issuecomment',
    ),
    "seerr_requests": (
        'seerr_create_request',
        'seerr_delete_request',
        'seerr_get_request',
        'seerr_list_request',
        'seerr_list_request_count',
        'seerr_retry_request',
        'seerr_set_request_status',
        'seerr_update_request',
    ),
    "seerr_blocklist": (
        'seerr_create_blocklist',
        'seerr_create_blocklist_collection',
        'seerr_delete_blocklist',
        'seerr_delete_blocklist_collection',
        'seerr_get_blocklist',
        'seerr_list_blocklist',
    ),
    "seerr_media_records": (
        'seerr_delete_media',
        'seerr_delete_media_file',
        'seerr_get_media_watch_data',
        'seerr_list_media',
        'seerr_set_media_status',
    ),
    "seerr_service_arr": (
        'seerr_get_service_radarr',
        'seerr_get_service_sonarr',
        'seerr_get_service_sonarr_lookup',
        'seerr_list_service_radarr',
        'seerr_list_service_sonarr',
    ),
    "seerr_override_rules": (
        'seerr_create_overriderule',
        'seerr_delete_overriderule',
        'seerr_list_overriderule',
        'seerr_update_overriderule',
    ),
    "seerr_search": (
        'seerr_list_search',
        'seerr_list_search_company',
        'seerr_list_search_keyword',
    ),
    "seerr_system_status": (
        'seerr_list_status',
        'seerr_list_status_appdata',
    ),
    "seerr_watchlist": (
        'seerr_create_watchlist',
        'seerr_delete_watchlist',
    ),
}


_TOOL_REGISTRY: list[dict[str, Any]] = [
 {'name': 'seerr_list_status',
  'method': 'GET',
  'path': '/status',
  'pp': [],
  'qp': [
          {'name': 'check_update_available', 'wire': 'checkUpdateAvailable', 'type': 'bool', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Get Seerr status',
 },
 {'name': 'seerr_list_status_appdata',
  'method': 'GET',
  'path': '/status/appdata',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get application data volume status',
 },
 {'name': 'seerr_list_settings_main',
  'method': 'GET',
  'path': '/settings/main',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get main settings',
 },
 {'name': 'seerr_create_settings_main',
  'method': 'POST',
  'path': '/settings/main',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update main settings WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_list_settings_network',
  'method': 'GET',
  'path': '/settings/network',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get network settings',
 },
 {'name': 'seerr_create_settings_network',
  'method': 'POST',
  'path': '/settings/network',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update network settings WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_regenerate_api_key',
  'method': 'POST',
  'path': '/settings/main/regenerate',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get main settings with newly-generated API key WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_list_settings_jellyfin',
  'method': 'GET',
  'path': '/settings/jellyfin',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get Jellyfin settings',
 },
 {'name': 'seerr_create_settings_jellyfin',
  'method': 'POST',
  'path': '/settings/jellyfin',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update Jellyfin settings WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_list_settings_jellyfin_library',
  'method': 'GET',
  'path': '/settings/jellyfin/library',
  'pp': [],
  'qp': [
          {'name': 'sync', 'wire': 'sync', 'type': 'str', 'default': None},
          {'name': 'enable', 'wire': 'enable', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Get Jellyfin libraries',
 },
 {'name': 'seerr_list_settings_jellyfin_users',
  'method': 'GET',
  'path': '/settings/jellyfin/users',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get Jellyfin Users',
 },
 {'name': 'seerr_list_settings_jellyfin_sync',
  'method': 'GET',
  'path': '/settings/jellyfin/sync',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get status of full Jellyfin library sync',
 },
 {'name': 'seerr_create_settings_jellyfin_sync',
  'method': 'POST',
  'path': '/settings/jellyfin/sync',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Start full Jellyfin library sync WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_list_settings_plex',
  'method': 'GET',
  'path': '/settings/plex',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get Plex settings',
 },
 {'name': 'seerr_create_settings_plex',
  'method': 'POST',
  'path': '/settings/plex',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update Plex settings WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_list_settings_plex_library',
  'method': 'GET',
  'path': '/settings/plex/library',
  'pp': [],
  'qp': [
          {'name': 'sync', 'wire': 'sync', 'type': 'str', 'default': None},
          {'name': 'enable', 'wire': 'enable', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Get Plex libraries',
 },
 {'name': 'seerr_list_settings_plex_sync',
  'method': 'GET',
  'path': '/settings/plex/sync',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get status of full Plex library scan',
 },
 {'name': 'seerr_create_settings_plex_sync',
  'method': 'POST',
  'path': '/settings/plex/sync',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Start full Plex library scan WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_list_settings_plex_devices_servers',
  'method': 'GET',
  'path': '/settings/plex/devices/servers',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': "Gets the user's available Plex servers",
 },
 {'name': 'seerr_list_settings_plex_users',
  'method': 'GET',
  'path': '/settings/plex/users',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get Plex users',
 },
 {'name': 'seerr_list_settings_metadatas',
  'method': 'GET',
  'path': '/settings/metadatas',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get Metadata settings',
 },
 {'name': 'seerr_update_settings_metadatas',
  'method': 'PUT',
  'path': '/settings/metadatas',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update Metadata settings WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_create_settings_metadatas_test',
  'method': 'POST',
  'path': '/settings/metadatas/test',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Test Provider configuration WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_list_settings_tautulli',
  'method': 'GET',
  'path': '/settings/tautulli',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get Tautulli settings',
 },
 {'name': 'seerr_create_settings_tautulli',
  'method': 'POST',
  'path': '/settings/tautulli',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update Tautulli settings WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_list_settings_radarr',
  'method': 'GET',
  'path': '/settings/radarr',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get Radarr settings',
 },
 {'name': 'seerr_create_settings_radarr',
  'method': 'POST',
  'path': '/settings/radarr',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create Radarr instance WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_create_settings_radarr_test',
  'method': 'POST',
  'path': '/settings/radarr/test',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Test Radarr configuration WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_update_settings_radarr',
  'method': 'PUT',
  'path': '/settings/radarr/{radarrId}',
  'pp': [
          {'name': 'radarr_id', 'wire': 'radarrId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update Radarr instance WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_delete_settings_radarr',
  'method': 'DELETE',
  'path': '/settings/radarr/{radarrId}',
  'pp': [
          {'name': 'radarr_id', 'wire': 'radarrId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete Radarr instance DESTRUCTIVE: this deletes data.',
 },
 {'name': 'seerr_get_settings_radarr_profiles',
  'method': 'GET',
  'path': '/settings/radarr/{radarrId}/profiles',
  'pp': [
          {'name': 'radarr_id', 'wire': 'radarrId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Get available Radarr profiles',
 },
 {'name': 'seerr_list_settings_sonarr',
  'method': 'GET',
  'path': '/settings/sonarr',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get Sonarr settings',
 },
 {'name': 'seerr_create_settings_sonarr',
  'method': 'POST',
  'path': '/settings/sonarr',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create Sonarr instance WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_create_settings_sonarr_test',
  'method': 'POST',
  'path': '/settings/sonarr/test',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Test Sonarr configuration WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_update_settings_sonarr',
  'method': 'PUT',
  'path': '/settings/sonarr/{sonarrId}',
  'pp': [
          {'name': 'sonarr_id', 'wire': 'sonarrId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update Sonarr instance WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_delete_settings_sonarr',
  'method': 'DELETE',
  'path': '/settings/sonarr/{sonarrId}',
  'pp': [
          {'name': 'sonarr_id', 'wire': 'sonarrId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete Sonarr instance DESTRUCTIVE: this deletes data.',
 },
 {'name': 'seerr_list_settings_public',
  'method': 'GET',
  'path': '/settings/public',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get public settings',
 },
 {'name': 'seerr_initialize_app',
  'method': 'POST',
  'path': '/settings/initialize',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Initialize application WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_list_settings_jobs',
  'method': 'GET',
  'path': '/settings/jobs',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get scheduled jobs',
 },
 {'name': 'seerr_run_job',
  'method': 'POST',
  'path': '/settings/jobs/{jobId}/run',
  'pp': [
          {'name': 'job_id', 'wire': 'jobId', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Invoke a specific job WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_cancel_job',
  'method': 'POST',
  'path': '/settings/jobs/{jobId}/cancel',
  'pp': [
          {'name': 'job_id', 'wire': 'jobId', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Cancel a specific job WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_schedule_job',
  'method': 'POST',
  'path': '/settings/jobs/{jobId}/schedule',
  'pp': [
          {'name': 'job_id', 'wire': 'jobId', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Modify job schedule WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_list_settings_cache',
  'method': 'GET',
  'path': '/settings/cache',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get a list of active caches',
 },
 {'name': 'seerr_flush_cache',
  'method': 'POST',
  'path': '/settings/cache/{cacheId}/flush',
  'pp': [
          {'name': 'cache_id', 'wire': 'cacheId', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Flush a specific cache WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_flush_dns_cache',
  'method': 'POST',
  'path': '/settings/cache/dns/{dnsEntry}/flush',
  'pp': [
          {'name': 'dns_entry', 'wire': 'dnsEntry', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Flush a specific DNS cache entry WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_list_settings_logs',
  'method': 'GET',
  'path': '/settings/logs',
  'pp': [],
  'qp': [
          {'name': 'take', 'wire': 'take', 'type': 'int', 'default': None},
          {'name': 'skip', 'wire': 'skip', 'type': 'int', 'default': None},
          {'name': 'filter', 'wire': 'filter', 'type': 'str', 'default': 'debug'},
          {'name': 'search', 'wire': 'search', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Returns logs',
 },
 {'name': 'seerr_list_settings_notifications_email',
  'method': 'GET',
  'path': '/settings/notifications/email',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get email notification settings',
 },
 {'name': 'seerr_create_settings_notifications_email',
  'method': 'POST',
  'path': '/settings/notifications/email',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update email notification settings WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_create_settings_notifications_email_test',
  'method': 'POST',
  'path': '/settings/notifications/email/test',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Test email settings WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_list_settings_notifications_discord',
  'method': 'GET',
  'path': '/settings/notifications/discord',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get Discord notification settings',
 },
 {'name': 'seerr_create_settings_notifications_discord',
  'method': 'POST',
  'path': '/settings/notifications/discord',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update Discord notification settings WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_create_settings_notifications_discord_test',
  'method': 'POST',
  'path': '/settings/notifications/discord/test',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Test Discord settings WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_list_settings_notifications_pushbullet',
  'method': 'GET',
  'path': '/settings/notifications/pushbullet',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get Pushbullet notification settings',
 },
 {'name': 'seerr_create_settings_notifications_pushbullet',
  'method': 'POST',
  'path': '/settings/notifications/pushbullet',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update Pushbullet notification settings WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_create_settings_notifications_pushbullet_test',
  'method': 'POST',
  'path': '/settings/notifications/pushbullet/test',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Test Pushbullet settings WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_list_settings_notifications_pushover',
  'method': 'GET',
  'path': '/settings/notifications/pushover',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get Pushover notification settings',
 },
 {'name': 'seerr_create_settings_notifications_pushover',
  'method': 'POST',
  'path': '/settings/notifications/pushover',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update Pushover notification settings WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_create_settings_notifications_pushover_test',
  'method': 'POST',
  'path': '/settings/notifications/pushover/test',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Test Pushover settings WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_list_pushover_sounds',
  'method': 'GET',
  'path': '/settings/notifications/pushover/sounds',
  'pp': [],
  'qp': [
          {'name': 'token', 'wire': 'token', 'type': 'str', 'default': None, 'required': True},
         ],
  'bk': 'none',
  'doc': 'Get Pushover sounds',
 },
 {'name': 'seerr_list_settings_notifications_gotify',
  'method': 'GET',
  'path': '/settings/notifications/gotify',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get Gotify notification settings',
 },
 {'name': 'seerr_create_settings_notifications_gotify',
  'method': 'POST',
  'path': '/settings/notifications/gotify',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update Gotify notification settings WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_create_settings_notifications_gotify_test',
  'method': 'POST',
  'path': '/settings/notifications/gotify/test',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Test Gotify settings WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_list_settings_notifications_ntfy',
  'method': 'GET',
  'path': '/settings/notifications/ntfy',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get ntfy.sh notification settings',
 },
 {'name': 'seerr_create_settings_notifications_ntfy',
  'method': 'POST',
  'path': '/settings/notifications/ntfy',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update ntfy.sh notification settings WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_create_settings_notifications_ntfy_test',
  'method': 'POST',
  'path': '/settings/notifications/ntfy/test',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Test ntfy.sh settings WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_list_settings_notifications_slack',
  'method': 'GET',
  'path': '/settings/notifications/slack',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get Slack notification settings',
 },
 {'name': 'seerr_create_settings_notifications_slack',
  'method': 'POST',
  'path': '/settings/notifications/slack',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update Slack notification settings WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_create_settings_notifications_slack_test',
  'method': 'POST',
  'path': '/settings/notifications/slack/test',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Test Slack settings WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_list_settings_notifications_telegram',
  'method': 'GET',
  'path': '/settings/notifications/telegram',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get Telegram notification settings',
 },
 {'name': 'seerr_create_settings_notifications_telegram',
  'method': 'POST',
  'path': '/settings/notifications/telegram',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update Telegram notification settings WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_create_settings_notifications_telegram_test',
  'method': 'POST',
  'path': '/settings/notifications/telegram/test',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Test Telegram settings WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_list_settings_notifications_webpush',
  'method': 'GET',
  'path': '/settings/notifications/webpush',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get Web Push notification settings',
 },
 {'name': 'seerr_create_settings_notifications_webpush',
  'method': 'POST',
  'path': '/settings/notifications/webpush',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update Web Push notification settings WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_create_settings_notifications_webpush_test',
  'method': 'POST',
  'path': '/settings/notifications/webpush/test',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Test Web Push settings WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_list_settings_notifications_webhook',
  'method': 'GET',
  'path': '/settings/notifications/webhook',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get webhook notification settings',
 },
 {'name': 'seerr_create_settings_notifications_webhook',
  'method': 'POST',
  'path': '/settings/notifications/webhook',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update webhook notification settings WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_create_settings_notifications_webhook_test',
  'method': 'POST',
  'path': '/settings/notifications/webhook/test',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Test webhook settings WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_list_discover_sliders',
  'method': 'GET',
  'path': '/settings/discover',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get all discover sliders',
 },
 {'name': 'seerr_update_discover_sliders',
  'method': 'POST',
  'path': '/settings/discover',
  'pp': [],
  'qp': [],
  'bk': 'list',
  'doc': 'Batch update all sliders. WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_update_discover_slider',
  'method': 'PUT',
  'path': '/settings/discover/{sliderId}',
  'pp': [
          {'name': 'slider_id', 'wire': 'sliderId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update a single slider WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_delete_discover_slider',
  'method': 'DELETE',
  'path': '/settings/discover/{sliderId}',
  'pp': [
          {'name': 'slider_id', 'wire': 'sliderId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete slider by ID DESTRUCTIVE: this deletes data.',
 },
 {'name': 'seerr_add_discover_slider',
  'method': 'POST',
  'path': '/settings/discover/add',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Add a new slider WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_reset_discover_sliders',
  'method': 'GET',
  'path': '/settings/discover/reset',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'force_write': True,
  'doc': 'Reset all discover sliders',
 },
 {'name': 'seerr_list_settings_about',
  'method': 'GET',
  'path': '/settings/about',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get server stats',
 },
 {'name': 'seerr_get_me',
  'method': 'GET',
  'path': '/auth/me',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get logged-in user',
 },
 {'name': 'seerr_login_plex',
  'method': 'POST',
  'path': '/auth/plex',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Sign in using a Plex token WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_login_jellyfin',
  'method': 'POST',
  'path': '/auth/jellyfin',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Sign in using a Jellyfin username and password WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_initiate_jellyfin_quickconnect',
  'method': 'POST',
  'path': '/auth/jellyfin/quickconnect/initiate',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Initiate Jellyfin Quick Connect WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_check_jellyfin_quickconnect',
  'method': 'GET',
  'path': '/auth/jellyfin/quickconnect/check',
  'pp': [],
  'qp': [
          {'name': 'secret', 'wire': 'secret', 'type': 'str', 'default': None, 'required': True},
         ],
  'bk': 'none',
  'doc': 'Check Quick Connect authorization status',
 },
 {'name': 'seerr_authenticate_jellyfin_quickconnect',
  'method': 'POST',
  'path': '/auth/jellyfin/quickconnect/authenticate',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Authenticate with Quick Connect WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_login_local',
  'method': 'POST',
  'path': '/auth/local',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Sign in using a local account WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_logout',
  'method': 'POST',
  'path': '/auth/logout',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Sign out and clear session cookie WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_request_password_reset',
  'method': 'POST',
  'path': '/auth/reset-password',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Send a reset password email WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_reset_password',
  'method': 'POST',
  'path': '/auth/reset-password/{guid}',
  'pp': [
          {'name': 'guid', 'wire': 'guid', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Reset the password for a user WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_list_user',
  'method': 'GET',
  'path': '/user',
  'pp': [],
  'qp': [
          {'name': 'take', 'wire': 'take', 'type': 'int', 'default': None},
          {'name': 'skip', 'wire': 'skip', 'type': 'int', 'default': None},
          {'name': 'sort', 'wire': 'sort', 'type': 'str', 'default': 'created'},
          {'name': 'sort_direction', 'wire': 'sortDirection', 'type': 'str', 'default': None},
          {'name': 'q', 'wire': 'q', 'type': 'str', 'default': None},
          {'name': 'include_ids', 'wire': 'includeIds', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Get all users',
 },
 {'name': 'seerr_create_user',
  'method': 'POST',
  'path': '/user',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create new user WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_batch_update_users',
  'method': 'PUT',
  'path': '/user',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update batch of users WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_import_plex_users',
  'method': 'POST',
  'path': '/user/import-from-plex',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Import all users from Plex WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_import_jellyfin_users',
  'method': 'POST',
  'path': '/user/import-from-jellyfin',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Import all users from Jellyfin WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_register_push_subscription',
  'method': 'POST',
  'path': '/user/registerPushSubscription',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Register a web push /user/registerPushSubscription WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_list_user_push_subscriptions',
  'method': 'GET',
  'path': '/user/{userId}/pushSubscriptions',
  'pp': [
          {'name': 'user_id', 'wire': 'userId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Get all web push notification settings for a user',
 },
 {'name': 'seerr_get_user_push_subscription',
  'method': 'GET',
  'path': '/user/{userId}/pushSubscription/{endpoint}',
  'pp': [
          {'name': 'user_id', 'wire': 'userId', 'type': 'int'},
          {'name': 'endpoint', 'wire': 'endpoint', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Get web push notification settings for a user',
 },
 {'name': 'seerr_delete_user_push_subscription',
  'method': 'DELETE',
  'path': '/user/{userId}/pushSubscription/{endpoint}',
  'pp': [
          {'name': 'user_id', 'wire': 'userId', 'type': 'int'},
          {'name': 'endpoint', 'wire': 'endpoint', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete user push subscription by key DESTRUCTIVE: this deletes data.',
 },
 {'name': 'seerr_get_user',
  'method': 'GET',
  'path': '/user/{userId}',
  'pp': [
          {'name': 'user_id', 'wire': 'userId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Get user by ID',
 },
 {'name': 'seerr_update_user',
  'method': 'PUT',
  'path': '/user/{userId}',
  'pp': [
          {'name': 'user_id', 'wire': 'userId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update a user by user ID WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_delete_user',
  'method': 'DELETE',
  'path': '/user/{userId}',
  'pp': [
          {'name': 'user_id', 'wire': 'userId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete user by ID DESTRUCTIVE: this deletes data.',
 },
 {'name': 'seerr_get_user_jellyfin',
  'method': 'GET',
  'path': '/user/jellyfin/{jellyfinUserId}',
  'pp': [
          {'name': 'jellyfin_user_id', 'wire': 'jellyfinUserId', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Get user by Jellyfin user ID',
 },
 {'name': 'seerr_get_user_requests',
  'method': 'GET',
  'path': '/user/{userId}/requests',
  'pp': [
          {'name': 'user_id', 'wire': 'userId', 'type': 'int'},
         ],
  'qp': [
          {'name': 'take', 'wire': 'take', 'type': 'int', 'default': None},
          {'name': 'skip', 'wire': 'skip', 'type': 'int', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Get requests for a specific user',
 },
 {'name': 'seerr_get_user_quota',
  'method': 'GET',
  'path': '/user/{userId}/quota',
  'pp': [
          {'name': 'user_id', 'wire': 'userId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Get quotas for a specific user',
 },
 {'name': 'seerr_list_blocklist',
  'method': 'GET',
  'path': '/blocklist',
  'pp': [],
  'qp': [
          {'name': 'take', 'wire': 'take', 'type': 'int', 'default': None},
          {'name': 'skip', 'wire': 'skip', 'type': 'int', 'default': None},
          {'name': 'search', 'wire': 'search', 'type': 'str', 'default': None},
          {'name': 'filter', 'wire': 'filter', 'type': 'str', 'default': 'manual'},
         ],
  'bk': 'none',
  'doc': 'Returns blocklisted items',
 },
 {'name': 'seerr_create_blocklist',
  'method': 'POST',
  'path': '/blocklist',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Add media to blocklist WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_get_blocklist',
  'method': 'GET',
  'path': '/blocklist/{tmdbId}',
  'pp': [
          {'name': 'tmdb_id', 'wire': 'tmdbId', 'type': 'str'},
         ],
  'qp': [
          {'name': 'media_type', 'wire': 'mediaType', 'type': 'str', 'default': None, 'required': True},
         ],
  'bk': 'none',
  'doc': 'Get media from blocklist',
 },
 {'name': 'seerr_delete_blocklist',
  'method': 'DELETE',
  'path': '/blocklist/{tmdbId}',
  'pp': [
          {'name': 'tmdb_id', 'wire': 'tmdbId', 'type': 'str'},
         ],
  'qp': [
          {'name': 'media_type', 'wire': 'mediaType', 'type': 'str', 'default': None, 'required': True},
         ],
  'bk': 'none',
  'doc': 'Remove media from blocklist DESTRUCTIVE: this deletes data.',
 },
 {'name': 'seerr_create_blocklist_collection',
  'method': 'POST',
  'path': '/blocklist/collection/{collectionId}',
  'pp': [
          {'name': 'collection_id', 'wire': 'collectionId', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Add collection to blocklist WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_delete_blocklist_collection',
  'method': 'DELETE',
  'path': '/blocklist/collection/{collectionId}',
  'pp': [
          {'name': 'collection_id', 'wire': 'collectionId', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Remove collection from blocklist DESTRUCTIVE: this deletes data.',
 },
 {'name': 'seerr_create_watchlist',
  'method': 'POST',
  'path': '/watchlist',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Add media to watchlist WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_delete_watchlist',
  'method': 'DELETE',
  'path': '/watchlist/{tmdbId}',
  'pp': [
          {'name': 'tmdb_id', 'wire': 'tmdbId', 'type': 'str'},
         ],
  'qp': [
          {'name': 'media_type', 'wire': 'mediaType', 'type': 'str', 'default': None, 'required': True},
         ],
  'bk': 'none',
  'doc': 'Delete watchlist item DESTRUCTIVE: this deletes data.',
 },
 {'name': 'seerr_get_user_watchlist',
  'method': 'GET',
  'path': '/user/{userId}/watchlist',
  'pp': [
          {'name': 'user_id', 'wire': 'userId', 'type': 'int'},
         ],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': 1},
         ],
  'bk': 'none',
  'doc': 'Get the Plex watchlist for a specific user',
 },
 {'name': 'seerr_get_user_settings_main',
  'method': 'GET',
  'path': '/user/{userId}/settings/main',
  'pp': [
          {'name': 'user_id', 'wire': 'userId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Get general settings for a user',
 },
 {'name': 'seerr_create_user_settings_main',
  'method': 'POST',
  'path': '/user/{userId}/settings/main',
  'pp': [
          {'name': 'user_id', 'wire': 'userId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update general settings for a user WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_get_user_settings_password',
  'method': 'GET',
  'path': '/user/{userId}/settings/password',
  'pp': [
          {'name': 'user_id', 'wire': 'userId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Get password page informatiom',
 },
 {'name': 'seerr_create_user_settings_password',
  'method': 'POST',
  'path': '/user/{userId}/settings/password',
  'pp': [
          {'name': 'user_id', 'wire': 'userId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update password for a user WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_create_user_settings_linked_accounts_plex',
  'method': 'POST',
  'path': '/user/{userId}/settings/linked-accounts/plex',
  'pp': [
          {'name': 'user_id', 'wire': 'userId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Link the provided Plex account to the current user WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_delete_user_settings_linked_accounts_plex',
  'method': 'DELETE',
  'path': '/user/{userId}/settings/linked-accounts/plex',
  'pp': [
          {'name': 'user_id', 'wire': 'userId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Remove the linked Plex account for a user DESTRUCTIVE: this deletes data.',
 },
 {'name': 'seerr_create_user_settings_linked_accounts_jellyfin',
  'method': 'POST',
  'path': '/user/{userId}/settings/linked-accounts/jellyfin',
  'pp': [
          {'name': 'user_id', 'wire': 'userId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Link the provided Jellyfin account to the current user WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_delete_user_settings_linked_accounts_jellyfin',
  'method': 'DELETE',
  'path': '/user/{userId}/settings/linked-accounts/jellyfin',
  'pp': [
          {'name': 'user_id', 'wire': 'userId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Remove the linked Jellyfin account for a user DESTRUCTIVE: this deletes data.',
 },
 {'name': 'seerr_create_user_settings_linked_accounts_jellyfin_quickconnect',
  'method': 'POST',
  'path': '/user/{userId}/settings/linked-accounts/jellyfin/quickconnect',
  'pp': [
          {'name': 'user_id', 'wire': 'userId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Link Jellyfin/Emby account with Quick Connect WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_get_user_settings_notifications',
  'method': 'GET',
  'path': '/user/{userId}/settings/notifications',
  'pp': [
          {'name': 'user_id', 'wire': 'userId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Get notification settings for a user',
 },
 {'name': 'seerr_create_user_settings_notifications',
  'method': 'POST',
  'path': '/user/{userId}/settings/notifications',
  'pp': [
          {'name': 'user_id', 'wire': 'userId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update notification settings for a user WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_get_user_settings_permissions',
  'method': 'GET',
  'path': '/user/{userId}/settings/permissions',
  'pp': [
          {'name': 'user_id', 'wire': 'userId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Get permission settings for a user',
 },
 {'name': 'seerr_create_user_settings_permissions',
  'method': 'POST',
  'path': '/user/{userId}/settings/permissions',
  'pp': [
          {'name': 'user_id', 'wire': 'userId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update permission settings for a user WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_get_user_watch_data',
  'method': 'GET',
  'path': '/user/{userId}/watch_data',
  'pp': [
          {'name': 'user_id', 'wire': 'userId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Get watch data',
 },
 {'name': 'seerr_list_search',
  'method': 'GET',
  'path': '/search',
  'pp': [],
  'qp': [
          {'name': 'query', 'wire': 'query', 'type': 'str', 'default': None, 'required': True},
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': 1},
          {'name': 'language', 'wire': 'language', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Search for movies, TV shows, or people',
 },
 {'name': 'seerr_list_search_keyword',
  'method': 'GET',
  'path': '/search/keyword',
  'pp': [],
  'qp': [
          {'name': 'query', 'wire': 'query', 'type': 'str', 'default': None, 'required': True},
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': 1},
         ],
  'bk': 'none',
  'doc': 'Search for keywords',
 },
 {'name': 'seerr_list_search_company',
  'method': 'GET',
  'path': '/search/company',
  'pp': [],
  'qp': [
          {'name': 'query', 'wire': 'query', 'type': 'str', 'default': None, 'required': True},
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': 1},
         ],
  'bk': 'none',
  'doc': 'Search for companies',
 },
 {'name': 'seerr_list_discover_movies',
  'method': 'GET',
  'path': '/discover/movies',
  'pp': [],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': 1},
          {'name': 'language', 'wire': 'language', 'type': 'str', 'default': None},
          {'name': 'genre', 'wire': 'genre', 'type': 'str', 'default': None},
          {'name': 'studio', 'wire': 'studio', 'type': 'int', 'default': None},
          {'name': 'keywords', 'wire': 'keywords', 'type': 'str', 'default': None},
          {'name': 'exclude_keywords', 'wire': 'excludeKeywords', 'type': 'str', 'default': None},
          {'name': 'sort_by', 'wire': 'sortBy', 'type': 'str', 'default': None},
          {'name': 'primary_release_date_gte', 'wire': 'primaryReleaseDateGte', 'type': 'str', 'default': None},
          {'name': 'primary_release_date_lte', 'wire': 'primaryReleaseDateLte', 'type': 'str', 'default': None},
          {'name': 'with_runtime_gte', 'wire': 'withRuntimeGte', 'type': 'int', 'default': None},
          {'name': 'with_runtime_lte', 'wire': 'withRuntimeLte', 'type': 'int', 'default': None},
          {'name': 'vote_average_gte', 'wire': 'voteAverageGte', 'type': 'int', 'default': None},
          {'name': 'vote_average_lte', 'wire': 'voteAverageLte', 'type': 'int', 'default': None},
          {'name': 'vote_count_gte', 'wire': 'voteCountGte', 'type': 'int', 'default': None},
          {'name': 'vote_count_lte', 'wire': 'voteCountLte', 'type': 'int', 'default': None},
          {'name': 'watch_region', 'wire': 'watchRegion', 'type': 'str', 'default': None},
          {'name': 'watch_providers', 'wire': 'watchProviders', 'type': 'str', 'default': None},
          {'name': 'certification', 'wire': 'certification', 'type': 'str', 'default': None},
          {'name': 'certification_gte', 'wire': 'certificationGte', 'type': 'str', 'default': None},
          {'name': 'certification_lte', 'wire': 'certificationLte', 'type': 'str', 'default': None},
          {'name': 'certification_country', 'wire': 'certificationCountry', 'type': 'str', 'default': None},
          {'name': 'certification_mode', 'wire': 'certificationMode', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Discover movies',
 },
 {'name': 'seerr_get_discover_movies_genre',
  'method': 'GET',
  'path': '/discover/movies/genre/{genreId}',
  'pp': [
          {'name': 'genre_id', 'wire': 'genreId', 'type': 'str'},
         ],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': 1},
          {'name': 'language', 'wire': 'language', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Discover movies by genre',
 },
 {'name': 'seerr_get_discover_movies_language',
  'method': 'GET',
  'path': '/discover/movies/language/{language}',
  'pp': [
          {'name': 'language', 'wire': 'language', 'type': 'str'},
         ],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': 1},
          {'name': 'language_q', 'wire': 'language', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Discover movies by original language',
 },
 {'name': 'seerr_get_discover_movies_studio',
  'method': 'GET',
  'path': '/discover/movies/studio/{studioId}',
  'pp': [
          {'name': 'studio_id', 'wire': 'studioId', 'type': 'str'},
         ],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': 1},
          {'name': 'language', 'wire': 'language', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Discover movies by studio',
 },
 {'name': 'seerr_list_discover_movies_upcoming',
  'method': 'GET',
  'path': '/discover/movies/upcoming',
  'pp': [],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': 1},
          {'name': 'language', 'wire': 'language', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Upcoming movies',
 },
 {'name': 'seerr_list_discover_tv',
  'method': 'GET',
  'path': '/discover/tv',
  'pp': [],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': 1},
          {'name': 'language', 'wire': 'language', 'type': 'str', 'default': None},
          {'name': 'genre', 'wire': 'genre', 'type': 'str', 'default': None},
          {'name': 'network', 'wire': 'network', 'type': 'int', 'default': None},
          {'name': 'keywords', 'wire': 'keywords', 'type': 'str', 'default': None},
          {'name': 'exclude_keywords', 'wire': 'excludeKeywords', 'type': 'str', 'default': None},
          {'name': 'sort_by', 'wire': 'sortBy', 'type': 'str', 'default': None},
          {'name': 'first_air_date_gte', 'wire': 'firstAirDateGte', 'type': 'str', 'default': None},
          {'name': 'first_air_date_lte', 'wire': 'firstAirDateLte', 'type': 'str', 'default': None},
          {'name': 'with_runtime_gte', 'wire': 'withRuntimeGte', 'type': 'int', 'default': None},
          {'name': 'with_runtime_lte', 'wire': 'withRuntimeLte', 'type': 'int', 'default': None},
          {'name': 'vote_average_gte', 'wire': 'voteAverageGte', 'type': 'int', 'default': None},
          {'name': 'vote_average_lte', 'wire': 'voteAverageLte', 'type': 'int', 'default': None},
          {'name': 'vote_count_gte', 'wire': 'voteCountGte', 'type': 'int', 'default': None},
          {'name': 'vote_count_lte', 'wire': 'voteCountLte', 'type': 'int', 'default': None},
          {'name': 'watch_region', 'wire': 'watchRegion', 'type': 'str', 'default': None},
          {'name': 'watch_providers', 'wire': 'watchProviders', 'type': 'str', 'default': None},
          {'name': 'status', 'wire': 'status', 'type': 'str', 'default': None},
          {'name': 'certification', 'wire': 'certification', 'type': 'str', 'default': None},
          {'name': 'certification_gte', 'wire': 'certificationGte', 'type': 'str', 'default': None},
          {'name': 'certification_lte', 'wire': 'certificationLte', 'type': 'str', 'default': None},
          {'name': 'certification_country', 'wire': 'certificationCountry', 'type': 'str', 'default': None},
          {'name': 'certification_mode', 'wire': 'certificationMode', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Discover TV shows',
 },
 {'name': 'seerr_get_discover_tv_language',
  'method': 'GET',
  'path': '/discover/tv/language/{language}',
  'pp': [
          {'name': 'language', 'wire': 'language', 'type': 'str'},
         ],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': 1},
          {'name': 'language_q', 'wire': 'language', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Discover TV shows by original language',
 },
 {'name': 'seerr_get_discover_tv_genre',
  'method': 'GET',
  'path': '/discover/tv/genre/{genreId}',
  'pp': [
          {'name': 'genre_id', 'wire': 'genreId', 'type': 'str'},
         ],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': 1},
          {'name': 'language', 'wire': 'language', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Discover TV shows by genre',
 },
 {'name': 'seerr_get_discover_tv_network',
  'method': 'GET',
  'path': '/discover/tv/network/{networkId}',
  'pp': [
          {'name': 'network_id', 'wire': 'networkId', 'type': 'str'},
         ],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': 1},
          {'name': 'language', 'wire': 'language', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Discover TV shows by network',
 },
 {'name': 'seerr_list_discover_tv_upcoming',
  'method': 'GET',
  'path': '/discover/tv/upcoming',
  'pp': [],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': 1},
          {'name': 'language', 'wire': 'language', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Discover Upcoming TV shows',
 },
 {'name': 'seerr_list_discover_trending',
  'method': 'GET',
  'path': '/discover/trending',
  'pp': [],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': 1},
          {'name': 'language', 'wire': 'language', 'type': 'str', 'default': None},
          {'name': 'media_type', 'wire': 'mediaType', 'type': 'str', 'default': 'all'},
          {'name': 'time_window', 'wire': 'timeWindow', 'type': 'str', 'default': 'day'},
         ],
  'bk': 'none',
  'doc': 'Trending movies and TV',
 },
 {'name': 'seerr_get_discover_keyword_movies',
  'method': 'GET',
  'path': '/discover/keyword/{keywordId}/movies',
  'pp': [
          {'name': 'keyword_id', 'wire': 'keywordId', 'type': 'int'},
         ],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': 1},
          {'name': 'language', 'wire': 'language', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Get movies from keyword',
 },
 {'name': 'seerr_list_discover_genreslider_movie',
  'method': 'GET',
  'path': '/discover/genreslider/movie',
  'pp': [],
  'qp': [
          {'name': 'language', 'wire': 'language', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Get genre slider data for movies',
 },
 {'name': 'seerr_list_discover_genreslider_tv',
  'method': 'GET',
  'path': '/discover/genreslider/tv',
  'pp': [],
  'qp': [
          {'name': 'language', 'wire': 'language', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Get genre slider data for TV series',
 },
 {'name': 'seerr_list_discover_watchlist',
  'method': 'GET',
  'path': '/discover/watchlist',
  'pp': [],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': 1},
         ],
  'bk': 'none',
  'doc': 'Get the Plex watchlist.',
 },
 {'name': 'seerr_list_request',
  'method': 'GET',
  'path': '/request',
  'pp': [],
  'qp': [
          {'name': 'take', 'wire': 'take', 'type': 'int', 'default': None},
          {'name': 'skip', 'wire': 'skip', 'type': 'int', 'default': None},
          {'name': 'filter', 'wire': 'filter', 'type': 'str', 'default': None},
          {'name': 'sort', 'wire': 'sort', 'type': 'str', 'default': 'added'},
          {'name': 'sort_direction', 'wire': 'sortDirection', 'type': 'str', 'default': 'desc'},
          {'name': 'requested_by', 'wire': 'requestedBy', 'type': 'int', 'default': None},
          {'name': 'media_type', 'wire': 'mediaType', 'type': 'str', 'default': 'all'},
         ],
  'bk': 'none',
  'doc': 'Get all requests',
 },
 {'name': 'seerr_create_request',
  'method': 'POST',
  'path': '/request',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create new request WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_list_request_count',
  'method': 'GET',
  'path': '/request/count',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Gets request counts',
 },
 {'name': 'seerr_get_request',
  'method': 'GET',
  'path': '/request/{requestId}',
  'pp': [
          {'name': 'request_id', 'wire': 'requestId', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Get MediaRequest',
 },
 {'name': 'seerr_update_request',
  'method': 'PUT',
  'path': '/request/{requestId}',
  'pp': [
          {'name': 'request_id', 'wire': 'requestId', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update MediaRequest WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_delete_request',
  'method': 'DELETE',
  'path': '/request/{requestId}',
  'pp': [
          {'name': 'request_id', 'wire': 'requestId', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete request DESTRUCTIVE: this deletes data.',
 },
 {'name': 'seerr_retry_request',
  'method': 'POST',
  'path': '/request/{requestId}/retry',
  'pp': [
          {'name': 'request_id', 'wire': 'requestId', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Retry failed request WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_set_request_status',
  'method': 'POST',
  'path': '/request/{requestId}/{status}',
  'pp': [
          {'name': 'request_id', 'wire': 'requestId', 'type': 'str'},
          {'name': 'status', 'wire': 'status', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': "Update a request's status WRITE: this modifies your Seerr instance.",
 },
 {'name': 'seerr_get_movie',
  'method': 'GET',
  'path': '/movie/{movieId}',
  'pp': [
          {'name': 'movie_id', 'wire': 'movieId', 'type': 'int'},
         ],
  'qp': [
          {'name': 'language', 'wire': 'language', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Get movie details',
 },
 {'name': 'seerr_get_movie_recommendations',
  'method': 'GET',
  'path': '/movie/{movieId}/recommendations',
  'pp': [
          {'name': 'movie_id', 'wire': 'movieId', 'type': 'int'},
         ],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': 1},
          {'name': 'language', 'wire': 'language', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Get recommended movies',
 },
 {'name': 'seerr_get_movie_similar',
  'method': 'GET',
  'path': '/movie/{movieId}/similar',
  'pp': [
          {'name': 'movie_id', 'wire': 'movieId', 'type': 'int'},
         ],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': 1},
          {'name': 'language', 'wire': 'language', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Get similar movies',
 },
 {'name': 'seerr_get_movie_ratings',
  'method': 'GET',
  'path': '/movie/{movieId}/ratings',
  'pp': [
          {'name': 'movie_id', 'wire': 'movieId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Get movie ratings',
 },
 {'name': 'seerr_get_movie_ratingscombined',
  'method': 'GET',
  'path': '/movie/{movieId}/ratingscombined',
  'pp': [
          {'name': 'movie_id', 'wire': 'movieId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Get RT and IMDB movie ratings combined',
 },
 {'name': 'seerr_get_tv',
  'method': 'GET',
  'path': '/tv/{tvId}',
  'pp': [
          {'name': 'tv_id', 'wire': 'tvId', 'type': 'int'},
         ],
  'qp': [
          {'name': 'language', 'wire': 'language', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Get TV details',
 },
 {'name': 'seerr_get_tv_season',
  'method': 'GET',
  'path': '/tv/{tvId}/season/{seasonNumber}',
  'pp': [
          {'name': 'tv_id', 'wire': 'tvId', 'type': 'int'},
          {'name': 'season_number', 'wire': 'seasonNumber', 'type': 'int'},
         ],
  'qp': [
          {'name': 'language', 'wire': 'language', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Get season details and episode list',
 },
 {'name': 'seerr_get_tv_recommendations',
  'method': 'GET',
  'path': '/tv/{tvId}/recommendations',
  'pp': [
          {'name': 'tv_id', 'wire': 'tvId', 'type': 'int'},
         ],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': 1},
          {'name': 'language', 'wire': 'language', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Get recommended TV series',
 },
 {'name': 'seerr_get_tv_similar',
  'method': 'GET',
  'path': '/tv/{tvId}/similar',
  'pp': [
          {'name': 'tv_id', 'wire': 'tvId', 'type': 'int'},
         ],
  'qp': [
          {'name': 'page', 'wire': 'page', 'type': 'int', 'default': 1},
          {'name': 'language', 'wire': 'language', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Get similar TV series',
 },
 {'name': 'seerr_get_tv_ratings',
  'method': 'GET',
  'path': '/tv/{tvId}/ratings',
  'pp': [
          {'name': 'tv_id', 'wire': 'tvId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Get TV ratings',
 },
 {'name': 'seerr_get_person',
  'method': 'GET',
  'path': '/person/{personId}',
  'pp': [
          {'name': 'person_id', 'wire': 'personId', 'type': 'int'},
         ],
  'qp': [
          {'name': 'language', 'wire': 'language', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Get person details',
 },
 {'name': 'seerr_get_person_combined_credits',
  'method': 'GET',
  'path': '/person/{personId}/combined_credits',
  'pp': [
          {'name': 'person_id', 'wire': 'personId', 'type': 'int'},
         ],
  'qp': [
          {'name': 'language', 'wire': 'language', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Get combined credits',
 },
 {'name': 'seerr_list_media',
  'method': 'GET',
  'path': '/media',
  'pp': [],
  'qp': [
          {'name': 'take', 'wire': 'take', 'type': 'int', 'default': None},
          {'name': 'skip', 'wire': 'skip', 'type': 'int', 'default': None},
          {'name': 'filter', 'wire': 'filter', 'type': 'str', 'default': None},
          {'name': 'sort', 'wire': 'sort', 'type': 'str', 'default': 'added'},
         ],
  'bk': 'none',
  'doc': 'Get media',
 },
 {'name': 'seerr_delete_media',
  'method': 'DELETE',
  'path': '/media/{mediaId}',
  'pp': [
          {'name': 'media_id', 'wire': 'mediaId', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete media item DESTRUCTIVE: this deletes data.',
 },
 {'name': 'seerr_delete_media_file',
  'method': 'DELETE',
  'path': '/media/{mediaId}/file',
  'pp': [
          {'name': 'media_id', 'wire': 'mediaId', 'type': 'str'},
         ],
  'qp': [
          {'name': 'is4k', 'wire': 'is4k', 'type': 'bool', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Delete media file DESTRUCTIVE: this deletes data.',
 },
 {'name': 'seerr_set_media_status',
  'method': 'POST',
  'path': '/media/{mediaId}/{status}',
  'pp': [
          {'name': 'media_id', 'wire': 'mediaId', 'type': 'str'},
          {'name': 'status', 'wire': 'status', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update media status WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_get_media_watch_data',
  'method': 'GET',
  'path': '/media/{mediaId}/watch_data',
  'pp': [
          {'name': 'media_id', 'wire': 'mediaId', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Get watch data',
 },
 {'name': 'seerr_get_collection',
  'method': 'GET',
  'path': '/collection/{collectionId}',
  'pp': [
          {'name': 'collection_id', 'wire': 'collectionId', 'type': 'int'},
         ],
  'qp': [
          {'name': 'language', 'wire': 'language', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Get collection details',
 },
 {'name': 'seerr_list_service_radarr',
  'method': 'GET',
  'path': '/service/radarr',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get non-sensitive Radarr server list',
 },
 {'name': 'seerr_get_service_radarr',
  'method': 'GET',
  'path': '/service/radarr/{radarrId}',
  'pp': [
          {'name': 'radarr_id', 'wire': 'radarrId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Get Radarr server quality profiles and root folders',
 },
 {'name': 'seerr_list_service_sonarr',
  'method': 'GET',
  'path': '/service/sonarr',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get non-sensitive Sonarr server list',
 },
 {'name': 'seerr_get_service_sonarr',
  'method': 'GET',
  'path': '/service/sonarr/{sonarrId}',
  'pp': [
          {'name': 'sonarr_id', 'wire': 'sonarrId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Get Sonarr server quality profiles and root folders',
 },
 {'name': 'seerr_get_service_sonarr_lookup',
  'method': 'GET',
  'path': '/service/sonarr/lookup/{tmdbId}',
  'pp': [
          {'name': 'tmdb_id', 'wire': 'tmdbId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Get series from Sonarr',
 },
 {'name': 'seerr_list_regions',
  'method': 'GET',
  'path': '/regions',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Regions supported by TMDB',
 },
 {'name': 'seerr_list_languages',
  'method': 'GET',
  'path': '/languages',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Languages supported by TMDB',
 },
 {'name': 'seerr_get_studio',
  'method': 'GET',
  'path': '/studio/{studioId}',
  'pp': [
          {'name': 'studio_id', 'wire': 'studioId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Get movie studio details',
 },
 {'name': 'seerr_get_network',
  'method': 'GET',
  'path': '/network/{networkId}',
  'pp': [
          {'name': 'network_id', 'wire': 'networkId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Get TV network details',
 },
 {'name': 'seerr_list_genres_movie',
  'method': 'GET',
  'path': '/genres/movie',
  'pp': [],
  'qp': [
          {'name': 'language', 'wire': 'language', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Get list of official TMDB movie genres',
 },
 {'name': 'seerr_list_genres_tv',
  'method': 'GET',
  'path': '/genres/tv',
  'pp': [],
  'qp': [
          {'name': 'language', 'wire': 'language', 'type': 'str', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Get list of official TMDB movie genres',
 },
 {'name': 'seerr_list_backdrops',
  'method': 'GET',
  'path': '/backdrops',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get backdrops of trending items',
 },
 {'name': 'seerr_list_issue',
  'method': 'GET',
  'path': '/issue',
  'pp': [],
  'qp': [
          {'name': 'take', 'wire': 'take', 'type': 'int', 'default': None},
          {'name': 'skip', 'wire': 'skip', 'type': 'int', 'default': None},
          {'name': 'sort', 'wire': 'sort', 'type': 'str', 'default': 'added'},
          {'name': 'filter', 'wire': 'filter', 'type': 'str', 'default': 'open'},
          {'name': 'requested_by', 'wire': 'requestedBy', 'type': 'int', 'default': None},
         ],
  'bk': 'none',
  'doc': 'Get all issues',
 },
 {'name': 'seerr_create_issue',
  'method': 'POST',
  'path': '/issue',
  'pp': [],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create new issue WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_list_issue_count',
  'method': 'GET',
  'path': '/issue/count',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Gets issue counts',
 },
 {'name': 'seerr_get_issue',
  'method': 'GET',
  'path': '/issue/{issueId}',
  'pp': [
          {'name': 'issue_id', 'wire': 'issueId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Get issue',
 },
 {'name': 'seerr_delete_issue',
  'method': 'DELETE',
  'path': '/issue/{issueId}',
  'pp': [
          {'name': 'issue_id', 'wire': 'issueId', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete issue DESTRUCTIVE: this deletes data.',
 },
 {'name': 'seerr_create_issue_comment',
  'method': 'POST',
  'path': '/issue/{issueId}/comment',
  'pp': [
          {'name': 'issue_id', 'wire': 'issueId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Create a comment WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_get_issuecomment',
  'method': 'GET',
  'path': '/issueComment/{commentId}',
  'pp': [
          {'name': 'comment_id', 'wire': 'commentId', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Get issue comment',
 },
 {'name': 'seerr_update_issuecomment',
  'method': 'PUT',
  'path': '/issueComment/{commentId}',
  'pp': [
          {'name': 'comment_id', 'wire': 'commentId', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'dict',
  'doc': 'Update issue comment WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_delete_issuecomment',
  'method': 'DELETE',
  'path': '/issueComment/{commentId}',
  'pp': [
          {'name': 'comment_id', 'wire': 'commentId', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete issue comment DESTRUCTIVE: this deletes data.',
 },
 {'name': 'seerr_set_issue_status',
  'method': 'POST',
  'path': '/issue/{issueId}/{status}',
  'pp': [
          {'name': 'issue_id', 'wire': 'issueId', 'type': 'str'},
          {'name': 'status', 'wire': 'status', 'type': 'str'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': "Update an issue's status WRITE: this modifies your Seerr instance.",
 },
 {'name': 'seerr_get_keyword',
  'method': 'GET',
  'path': '/keyword/{keywordId}',
  'pp': [
          {'name': 'keyword_id', 'wire': 'keywordId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Get keyword',
 },
 {'name': 'seerr_list_watchproviders_regions',
  'method': 'GET',
  'path': '/watchproviders/regions',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get watch provider regions',
 },
 {'name': 'seerr_list_watchproviders_movies',
  'method': 'GET',
  'path': '/watchproviders/movies',
  'pp': [],
  'qp': [
          {'name': 'watch_region', 'wire': 'watchRegion', 'type': 'str', 'default': None, 'required': True},
         ],
  'bk': 'none',
  'doc': 'Get watch provider movies',
 },
 {'name': 'seerr_list_watchproviders_tv',
  'method': 'GET',
  'path': '/watchproviders/tv',
  'pp': [],
  'qp': [
          {'name': 'watch_region', 'wire': 'watchRegion', 'type': 'str', 'default': None, 'required': True},
         ],
  'bk': 'none',
  'doc': 'Get watch provider series',
 },
 {'name': 'seerr_list_certifications_movie',
  'method': 'GET',
  'path': '/certifications/movie',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get movie certifications',
 },
 {'name': 'seerr_list_certifications_tv',
  'method': 'GET',
  'path': '/certifications/tv',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get TV certifications',
 },
 {'name': 'seerr_list_overriderule',
  'method': 'GET',
  'path': '/overrideRule',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Get override rules',
 },
 {'name': 'seerr_create_overriderule',
  'method': 'POST',
  'path': '/overrideRule',
  'pp': [],
  'qp': [],
  'bk': 'none',
  'doc': 'Create override rule WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_update_overriderule',
  'method': 'PUT',
  'path': '/overrideRule/{ruleId}',
  'pp': [
          {'name': 'rule_id', 'wire': 'ruleId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Update override rule WRITE: this modifies your Seerr instance.',
 },
 {'name': 'seerr_delete_overriderule',
  'method': 'DELETE',
  'path': '/overrideRule/{ruleId}',
  'pp': [
          {'name': 'rule_id', 'wire': 'ruleId', 'type': 'int'},
         ],
  'qp': [],
  'bk': 'none',
  'doc': 'Delete override rule by ID DESTRUCTIVE: this deletes data.',
 },
]


def _tool_source(spec: dict[str, Any]) -> str:
    parts: list[str] = []
    for p in spec["pp"]:
        parts.append(f"{p['name']}: {p['type']}")
    for q in spec["qp"]:
        if q.get("required"):
            parts.append(f"{q['name']}: {q['type']}")
        else:
            parts.append(f"{q['name']}: {q['type']} = {q['default']!r}")
    if spec["bk"] == "dict":
        parts.append("body: dict[str, Any] = {}")
    elif spec["bk"] == "list":
        parts.append("body: list[Any] = []")
    sig = ", ".join(parts)

    path_tmpl = spec["path"]
    for p in spec["pp"]:
        path_tmpl = path_tmpl.replace("{" + p["wire"] + "}", "{" + p["name"] + "}")
    if spec["pp"]:
        arg_call = ", ".join(f"{p['name']}=quote(str({p['name']}))" for p in spec["pp"])
        url_expr = f'"{path_tmpl}".format({arg_call})'
    else:
        url_expr = repr(spec["path"])

    optional = [q for q in spec["qp"] if not q.get("required")]
    required = [q for q in spec["qp"] if q.get("required")]
    if optional:
        params_expr = "_omit({" + ", ".join(f'"{q["wire"]}": {q["name"]}' for q in optional) + "})"
        if required:
            params_expr += " | " + "{" + ", ".join(f'"{q["wire"]}": {q["name"]}' for q in required) + "}"
    elif required:
        params_expr = "{" + ", ".join(f'"{q["wire"]}": {q["name"]}' for q in required) + "}"
    else:
        params_expr = "None"
    json_expr = "body" if spec["bk"] != "none" else "None"

    doc = spec["doc"].replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    return (
        f"async def {spec['name']}({sig}) -> JSONVal:\n"
        f'    """{doc}"""\n'
        f"    return await _req({spec['method']!r}, {url_expr}, params={params_expr}, json_body={json_expr})\n"
    )


def _op_line(name: str, fn: Any, force_write: bool) -> str:
    """One line of a group tool's description: signature + one-line doc."""
    sig = ", ".join(
        p.name if p.default is inspect.Parameter.empty else f"{p.name}={p.default!r}"
        for p in inspect.signature(fn).parameters.values()
    )
    note = " (WRITE — a GET that mutates state)" if force_write else ""
    return f"- {name}({sig}) — {' '.join((fn.__doc__ or '').split())}{note}"


def _register_group(group: str, names: tuple[str, ...], ns: dict[str, Any], spec_of: dict[str, dict[str, Any]]) -> None:
    """Register one dispatching tool that fans out to every endpoint function
    named in `names`. The endpoint functions themselves are untouched -
    they're just looked up by name instead of each becoming its own tool."""
    fns = {n: ns[n] for n in names}

    async def dispatch(operation: str, arguments: JSONObj | None = None) -> JSONVal:
        fn = fns.get(operation)
        if fn is None:
            raise ToolError(f"Unknown operation {operation!r} for {group}. Valid: {', '.join(fns)}")
        return await fn(**(arguments or {}))

    dispatch.__annotations__["operation"] = Literal[names]
    # force_write GETs (currently just seerr_reset_discover_sliders) count as
    # non-GET for the all-GET check, matching the original per-tool logic
    # that gave them WRITE instead of READONLY.
    effective_methods = {
        "WRITE" if spec_of[n].get("force_write") else spec_of[n]["method"] for n in names
    }
    ann = READONLY if effective_methods == {"GET"} else None
    mcp.add_tool(
        Tool.from_function(
            dispatch,
            name=group,
            description=(
                f"{group.replace('_', ' ')} operations on Seerr. Pass `operation` and an "
                f"`arguments` dict matching that operation's parameters.\n\n"
                + "\n".join(_op_line(n, f, spec_of[n].get("force_write", False)) for n, f in fns.items())
            ),
            annotations=ann,
        )
    )


def register_tools() -> None:
    src = "\n".join(_tool_source(spec) for spec in _TOOL_REGISTRY)
    ns: dict[str, Any] = {}
    exec(src, globals(), ns)
    spec_of = {spec["name"]: spec for spec in _TOOL_REGISTRY}
    for group, names in _GROUPS.items():
        _register_group(group, names, ns, spec_of)


register_tools()


def main() -> None:
    global _client
    url = os.environ.get("SEERR_URL")
    if not url:
        print("SEERR_URL environment variable is required (e.g. https://seerr.example.com)", file=sys.stderr)
        raise SystemExit(1)
    _client = build_client(url, os.environ.get("SEERR_API_KEY"), os.environ.get("SEERR_API_USER"))
    mcp.run()


if __name__ == "__main__":
    main()
